<?php
namespace backend\filters;

use yii\base\ActionFilter;
use yii\web\ForbiddenHttpException;

class Rbacfilters extends ActionFilter{
    //过滤器是一种特殊的行为,用来限制动作的请求
    public function beforeAction($action)
    {
        //当前访问的路由  $action->uniqueId
        if(!\Yii::$app->user->can($action->uniqueId)){
            //判断是否登录,如果用户没有登录,引导用户跳转到登录页面
            if(\Yii::$app->user->isGuest){
                \Yii::$app->session->setFlash('success','请登录后进行操作');
                return $action->controller->redirect(\Yii::$app->user->loginUrl)->send(); //需要加一个send()方法,不然会返回true
            }
            throw new ForbiddenHttpException('没有权限的操作!如需添加权限,请联系管理员');
        };
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}